### ISSUE TITLE
tiny-site没问题可以运行,  但是tiny还是报错了

### ISSUE THREAD

**Issue by KevinsDeveloper** [vicanso/tiny#2]
error while loading shared libraries: libbrotlicommon.so.1: cannot open shared object file: No such file or directory

**Comment by vicanso** [comment]
brotli压缩暂时没有纯golang的实现，是需要编译的，linux的方法可以参考[dockerfile](https://github.com/vicanso/tiny/blob/master/Dockerfile#L10)
